import Head from "next/head";
import { Layout } from "antd";
import { Menu } from "antd";
import {
  MailOutlined,
  AppstoreOutlined,
  SettingOutlined,
} from "@ant-design/icons";
const { Header, Footer, Sider, Content } = Layout;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header>
          <Menu theme="dark" mode="horizontal" defaultSelectedKeys={["mail"]}>
            <Menu.Item key="mail" icon={<MailOutlined />}>
              Navigation One
            </Menu.Item>
            <Menu.SubMenu
              key="SubMenu"
              title="Navigation Two - Submenu"
              icon={<SettingOutlined />}
            >
              <Menu.Item key="two" icon={<AppstoreOutlined />}>
                Navigation Two
              </Menu.Item>
              <Menu.Item key="three" icon={<AppstoreOutlined />}>
                Navigation Three
              </Menu.Item>
              <Menu.ItemGroup title="Item Group">
                <Menu.Item key="four" icon={<AppstoreOutlined />}>
                  Navigation Four
                </Menu.Item>
                <Menu.Item key="five" icon={<AppstoreOutlined />}>
                  Navigation Five
                </Menu.Item>
              </Menu.ItemGroup>
            </Menu.SubMenu>
          </Menu>
        </Header>
        <Content>
          Vivamus quis mi. Phasellus a est. Phasellus magna. In hac habitasse
          platea dictumst. Curabitur at lacus ac velit ornare lobortis.
          Curabitur a felis in nunc fringilla tristique. Morbi mattis
          ullamcorper velit. Phasellus gravida semper nisi. Nullam vel sem.
          Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec,
          quam. Sed hendrerit. Morbi ac felis.{" "}
        </Content>
        <Footer>Footer</Footer>
      </Layout>
    </div>
  );
}
